Collar me surprised
Fansana/floofstation1 pull request #105
Opened 2024-08-13 18:43 UTC by Memeji

# Description

This update adds some collars to the game. Many found in the various department wardrobe vendors.

---

# Changelog

:cl:
- add: Black Collar to Clothesmate
- add: Blue Collar Clothesmate
- add: CentCom Collar to CentDrobe
- add: Captain's Collar to the Uniform Printer
- add: Engineer Collar to EngiDrobe
- add: Epistemics Collar to SciDrobe
- add: Logistics Collar to CargoDrobe
- add: Medical Collar to MediDrobe
- add: Security Collar to SecDrobe
- add: Blood-Red Collar to SyndieDrobe

2024-08-13 18:51 UTC, FoxxoTrystan approved these changes

2024-08-13 18:51 UTC, FoxxoTrystan commented
All look good, tho do you think you could add those in "Loadout" also?
in the neck category.

2024-08-13 18:52 UTC, Memeji commented
> All look good, tho do you think you could add those in "Loadout" also? in the neck category.

Doing so now! Didn't notice it till I already submitted it so I'll quickly get them added.

2024-08-13 19:24 UTC, FoxxoTrystan requested changes

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/Heads/captain.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/cargo.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/engineering.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/medical.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/science.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/Jobs/security.yml
Please use the "Floof" folder.

2024-08-13 19:24 UTC, FoxxoTrystan commented on Resources/Prototypes/Loadouts/neck.yml
Please use the "Floof" folder.

2024-08-13 20:29 UTC, FoxxoTrystan approved these changes

2024-08-13 20:40 UTC, merged

2024-08-17 06:50 UTC, Mnemotechnician commented
This should absolutely be ported to EE

2024-08-17 13:14 UTC, FoxxoTrystan commented
> This should absolutely be ported to EE

Okay, go fight VM to add this.