Loadout Point Increase And Labcoat For All
Fansana/floofstation1 pull request #107
Opened 2024-08-14 04:20 UTC by ShatteredSwords

# Description

Adds the labcoat for everyone (the completely white one with no identifying colors), and increases the loadout points to 20. 
**(This NEEDS discussion unless you both agree on it)**

---

# Changelog

:cl:
- add: The lab coat is now available for everyone, because you can be a scientist without working in Epistemics.
- tweak: Loadout points have been increased from 14 to 20.

2024-08-14 05:12 UTC, FoxxoTrystan requested changes
Tail Fails are legits, this need to be fixed.

2024-08-14 05:12 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Loadouts/outerClothing.yml
> +  id: LoadoutOuter
Something tells me you put type and id in the wrong way.

2024-08-14 05:42 UTC, FoxxoTrystan approved these changes

2024-08-14 06:47 UTC, Fansana commented
Dunno I don't see a reason to bump the load out points right now.

2024-08-14 06:54 UTC, ShatteredSwords commented
> Dunno I don't see a reason to bump the load out points right now.

Currently for the sake of more customization (while EE gets the exclusion groups up) and because I am going to be adding a lot more roleplay-oriented items to Floof itself

2024-08-14 06:55 UTC, ShatteredSwords commented
> > Dunno I don't see a reason to bump the load out points right now.
> 
> Currently for the sake of more customization (while EE gets the exclusion groups up) and because I am going to be adding a lot more roleplay-oriented items to Floof itself

That being said, it's fine if you disagree, it's a pretty easy to just PR the lab coat :P

2024-08-14 07:12 UTC, Fansana commented
Mmmhh, I mean upping it a little shouldn't hurt. 16 would be fine for now I think. aside from that we can adjust the points required for certain items.

2024-08-14 23:53 UTC, merged

2024-08-15 07:10 UTC, ShatteredSwords commented
Please be sure to edit the CL next time, but all good, ty