Floofinization
Fansana/floofstation1 pull request #115
Opened 2024-08-16 23:13 UTC by ShatteredSwords

# Description

Seb became their own thing in the Floof folder, new Seb migrations, new Seb toy and Spawner, NNN was moved to Floof folder. This was cherry-picked from my more items branch, which will have to wait until we get the new Loadouts update from EE.

---

# Changelog

:cl:
- add: Seb Toy!
- add: Seb themselves!
- tweak: Siobhan exists again!
- tweak: All Floof Stations will have Seb!

2024-08-16 23:26 UTC, FoxxoTrystan requested changes

2024-08-16 23:26 UTC, FoxxoTrystan commented on Resources/Migrations/migration.yml
> +MobArcticFoxSiobhan: MobArcticFoxSeb
```suggestion

# 2024-08-16 Floof Only Please message @FracturedSwords on discord if there are any merge conflicts upcoming
SpawnMobArcticFoxSiobhan: SpawnMobArcticFoxSeb
MobArcticFoxSiobhan: MobArcticFoxSeb
```

We have support to use custom migration folders move it to "floofmigration"

2024-08-16 23:26 UTC, FoxxoTrystan commented on Resources/Migrations/migration.yml
> +MobArcticFoxSiobhan: MobArcticFoxSeb
now also the one above need also to be moved there, if not ported upstream.

2024-08-16 23:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Mobs/NPCs/pets.yml
You could just parent it off "Siobhan" instead of "MobArcticFox"

2024-08-16 23:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Objects/Fun/toys.yml
Due to this addtion, this PR will be put on hold until the upstream merge where the "Plushie Update" will bring, this should be modified to fit in the upcoming update.

2024-08-16 23:27 UTC, FoxxoTrystan commented
Changlog can be smaller then this, please try to compact changlogs.

2024-08-17 13:22 UTC, FoxxoTrystan requested changes

2024-08-17 13:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Objects/Fun/toys.yml
If this file is unused, its should be deleted.

2024-08-17 18:53 UTC, FoxxoTrystan approved these changes

2024-08-18 20:49 UTC, Memeji approved these changes

2024-08-18 21:19 UTC, merged