Clothing-nikko
Fansana/floofstation1 pull request #119
Opened 2024-08-18 17:29 UTC by Memeji

# Description

Added Coder Arm Warmers and a Pink Collar

---

# Changelog

:cl:
- add: Pink Collar
- add: Coder Arm Warmers

2024-08-18 19:58 UTC, ShatteredSwords commented
I think there are armwarmers being added in #116 in terms of coder stuff

2024-08-18 21:24 UTC, FoxxoTrystan requested changes
Coder Armes is already added, replace or remove.

2024-08-19 05:31 UTC, FoxxoTrystan approved these changes

2024-08-19 05:31 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/pride.yml
Normally this should be unchanged but its fine.

2024-08-19 05:33 UTC, merged