Clothing Additions By DakoDemon
Fansana/floofstation1 pull request #136
Opened 2024-08-22 18:11 UTC by ShatteredSwords

# Description

Added in some more departmental socks, and a few other requested outfits. Did a few bug fixes. - DakoDemon

(I helped solve the merge conflicts by cherry-picking each of these commits and manually going through! Hope I didn't fuck anything up!) -Kota aka ShatteredSwords

---

# Changelog

:cl: DakoDemon
- add: Added a few more outfits
- fix: Fixed the skirt issue for harpies
- fix: Fixed Sec armor values

2024-08-22 18:17 UTC, ShatteredSwords commented
Alright time to see what I did wrong :P

2024-08-22 20:34 UTC, Memeji reviewed
Seems good from what I see.
Only thing I'm wondering about is commenting out the old socks.
Also I believe a fix was applied for Sec values already while I was asleep.

2024-08-22 21:17 UTC, ShatteredSwords commented
> Seems good from what I see. Only thing I'm wondering about is commenting out the old socks. Also I believe a fix was applied for Sec values already while I was asleep.

Making the coder and bee socks cheaper because Dako put them in their own PR as a cheaper loadout, so keeping the other loadout would make it redundant

2024-08-22 21:19 UTC, ShatteredSwords commented
> Also I believe a fix was applied for Sec values already while I was asleep.

These ones still have a slight armor value as far as I can tell, if you want them coded out I could probably remove them just fine.

2024-08-22 23:47 UTC, Memeji approved these changes
Thanks for the info, overall looks good.

2024-08-23 00:30 UTC, FoxxoTrystan requested changes
Those clothing must NOT replace security, protective, job equipement and so should in any cases not have speed boosts or armor or special effects, keep them simple.

If someone need to have more project if handling something dangerous they should get protective gear for that moment.

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/pride.yml
> +       ClothingUniformThongBee: 1
```suggestion
       ClothingHandsBeeWarmers: 1 # Floofstation
       ClothingHandsCoderWarmers: 1 # Floofstation
       ClothingUniformThongCoder: 1 # Floofstation
       ClothingUniformThongBee: 1 # Floofstation
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/pride.yml
> +      ClothingUniformThongCoderValid: 3
```suggestion
      ClothingHandsCoderValidWarmers: 3 # Floofstation
      ClothingUniformThongCoderValid: 3 # Floofstation
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/robodrobe.yml
> +    ClothingOuterPlainOveralls: 2
```suggestion
    ClothingOuterPlainOveralls: 2 # Floofstation
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Slash: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +  - type: Insulated
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +    heatResistance: 1400
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +    heatResistance: 1400
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.85
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.85
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.85
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.85
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +    enabled: true
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Caustic: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +    enabled: true
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.95
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.9
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.9
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.9
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +    - Forensics
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +  description: A pair of rather nice arm-warmers, styled for a Detective. Does not leave Fibers or Fingerprints.
```suggestion
  description: A pair of rather nice arm-warmers, styled for a Detective.
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +  - type: FingerprintMask
This should not replace the detective equipement and so should have fiber.

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.9
```suggestion
```

2024-08-23 00:30 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
> +        Heat: 0.9
```suggestion
```

2024-08-23 00:41 UTC, ShatteredSwords commented
I'm gonna resolve these on PC so I don't have to handle a dying phone while merging the suggestions lol

2024-08-23 01:40 UTC, ShatteredSwords commented
So turns out github will test every single commit before testing the whole thing together. I ate all of the actions tests. Do not do what I did and learn the hard way, any contributor that may read this.

2024-08-23 03:27 UTC, FoxxoTrystan approved these changes

2024-08-23 19:49 UTC, Memeji approved these changes

2024-08-23 19:50 UTC, merged