Silly slimes
Fansana/floofstation1 pull request #144
Opened 2024-08-24 02:26 UTC by fenndragon

# Description

Changed the Sprites of 4 particular slimes

---

# Changelog

:cl:

-Changed 4 of the elemental sprites

2024-08-24 16:52 UTC, FoxxoTrystan requested changes
Should those sprites not be applied to the non-floof slimes also?

2024-08-24 16:52 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
> +  "copyright": "Created by TheShuEd (github) for Space Station 14.",
Please state the edit you did to the sprites.

Example: Edited by ...

2024-08-25 18:42 UTC, FoxxoTrystan approved these changes

2024-08-25 18:43 UTC, FoxxoTrystan requested changes
Please change the changlog, those seem to relate to all slimes.

2024-08-25 18:43 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
You need to reffer to anyone that did a change.

Orignal creator of the sprite + edited by ...

2024-08-26 10:18 UTC, fenndragon commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
*blinks* no, I specified that I changed 4 slimes sprites, there are only 2 sprites. 

there are 4 slimes that get those 2 sprites. it's pretty clear I didn't say I was changing all slimes

2024-08-26 10:18 UTC, fenndragon commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
also OH! we're doing credits on this stuff now? I... don't actually think I've put credits on any of the work I've done so far...

2024-08-26 18:30 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
You have to mention that you edited the sprites.

2024-08-26 18:41 UTC, fenndragon commented on Resources/Textures/Floof/Mobs/Animals/elemental.rsi/meta.json
where do I do this?

2024-08-27 19:41 UTC, FoxxoTrystan approved these changes

2024-08-27 19:41 UTC, FoxxoTrystan commented on Resources/Textures/Mobs/Aliens/Xenos/rouny.rsi/meta.json
This change is not related to the PR.
But il accept it.

2024-08-27 20:06 UTC, Memeji approved these changes

2024-08-27 20:07 UTC, merged