Update clothing assignments of suit/skirt
Fansana/floofstation1 pull request #146
Opened 2024-08-24 03:54 UTC by Tirochora

# Description

Changes some of the parent clothing for various outfits in the game, such as the colored jumpskirts, the monastic robes, the operative jumpskirt, and miscellaneous clothing pieces that have open bottoms such as the gladiator's outfit and the kimono.

---

# Changelog

:cl: 
- fix: basic colored jumpskirts, kimonos, monastic robes, and the operative jumpskirt all now have the jumpskirt parent (operative jumpskirt is still unsensored), meaning they should be able to be worn by harpies.

2024-08-24 16:41 UTC, FoxxoTrystan requested changes
This is going to be a nightmare with conflict merges.

Please add comments on changes
and move all new jumpskirts to the floof directory wil commenting the old ones instead of deleting them.

2024-09-01 13:06 UTC, Tirochora commented
> This is going to be a nightmare with conflict merges.
> 
> Please add comments on changes and move all new jumpskirts to the floof directory wil commenting the old ones instead of deleting them.

I'm not quite sure what you mean with 'moving all new jumpskirts to the floof directory, as there are no 'new' jumpskirts. Should I make and move the ones I modified to a separate 'jumpskirts.yml' in the floof directory?

2024-09-02 19:26 UTC, FoxxoTrystan requested changes

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +    sprite: Clothing/Uniforms/Jumpskirt/kimono.rsi
This need to be moved to a floof directory instead please.

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +# Moved this to jumpskirts.yml, further modifications made there.
```suggestion
# Moved this to jumpskirts.yml, further modifications made there. // FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +# Moved this to jumpskirts.yml, further modifications made there.
```suggestion
# Moved this to jumpskirts.yml, further modifications made there. // FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +# Moved this to jumpskirts.yml, further modifications made there.
```suggestion
# Moved this to jumpskirts.yml, further modifications made there. // FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +# Moved this to jumpskirts.yml, further modifications made there.
```suggestion
# Moved this to jumpskirts.yml, further modifications made there. // FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/specific.yml
> +  parent: ClothingUniformSkirtBase
```suggestion
  parent: ClothingUniformSkirtBase # FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
> +# Adds the 'skirt' tag to UnsensoredClothingUniformSkirtBase to, well, make it a skirt.
```suggestion
# Adds the 'skirt' tag to UnsensoredClothingUniformSkirtBase to, well, make it a skirt. // FloofStation
```

2024-09-02 19:26 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
> +# Removed the subsequent 'skirt' tag from ClothingUniformSkirtBase, as the unsensored parent now has it.
```suggestion
# Removed the subsequent 'skirt' tag from ClothingUniformSkirtBase, as the unsensored parent now has it. // FloofStation
```
Also doing this kinda make this base now worthless.

2024-09-13 03:32 UTC, Tirochora commented
I forgot to close this earlier - I brought this up to EE, as there's no reason not to and it makes things simpler.

2024-09-13 03:32 UTC, closed without merging