SEX TOYS
Fansana/floofstation1 pull request #154
Opened 2024-08-25 02:44 UTC by Memeji

# Description

This PR adds several vibrators, fleshlights, and dildos to the station. These can even be bought in the cargo catalogue for 1500 spessos!

---

# Changelog

:cl:
- add: Dildos
- add: Fleshlights
- add: Vibrators

2024-08-25 02:53 UTC, ShatteredSwords commented
You made the linter unhappy with "ammount" instead of "amount"

2024-08-25 18:14 UTC, FoxxoTrystan requested changes
Tests fails are valid.

2024-08-26 18:39 UTC, FoxxoTrystan requested changes
Test fails are still valid.

2024-08-26 19:09 UTC, Memeji commented
> Test fails are still valid.

Yes, I am still in the process of finding where they hard-coded the limit.
If you have any ideas, lemme know.

2024-08-26 19:25 UTC, FoxxoTrystan requested changes

2024-08-26 19:25 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
> +          prob: 0.02   # Floof - End
```suggestion
        - id: LewdWand # Floof - Start
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeGreen
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeTeal
          prob: 0.02
        - id: LewdVibePink
          prob: 0.02
        - id: LewdVibeRed
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeYellow
          prob: 0.02
        - id: LewdFleshlightGreen
          prob: 0.02
        - id: LewdFleshlightTeal
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightPink
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightRed
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightYellow
          prob: 0.02
          orGroup: Lewd
        - id: AvianDildo
          prob: 0.02
          orGroup: Lewd
        - id: CanineDildo
          prob: 0.02
          orGroup: Lewd
        - id: HorseDildo
          prob: 0.02
          orGroup: Lewd
        - id: DragonDildo
          prob: 0.02
          orGroup: Lewd
        - id: NormalDildo
          prob: 0.02
          orGroup: Lewd
        - id: TentacleDildo
          prob: 0.02
          orGroup: Lewd
        - id: DoubleDildo
          prob: 0.02   # Floof - End
          orGroup: Lewd
```

2024-08-26 19:25 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
> +          prob: 0.02  # Floof - End
```suggestion
        - id: LewdWand  # Floof - Start
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeGreen
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeTeal
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibePink
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeRed
          prob: 0.02
          orGroup: Lewd
        - id: LewdVibeYellow
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightGreen
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightTeal
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightPink
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightRed
          prob: 0.02
          orGroup: Lewd
        - id: LewdFleshlightYellow
          prob: 0.02
          orGroup: Lewd
        - id: AvianDildo
          prob: 0.02
          orGroup: Lewd
        - id: CanineDildo
          prob: 0.02
          orGroup: Lewd
        - id: HorseDildo
          prob: 0.02
          orGroup: Lewd
        - id: DragonDildo
          prob: 0.02
          orGroup: Lewd
        - id: NormalDildo
          prob: 0.02
          orGroup: Lewd
        - id: TentacleDildo
          prob: 0.02
          orGroup: Lewd
        - id: DoubleDildo
          prob: 0.02  # Floof - End
          orGroup: Lewd
```

2024-08-26 20:49 UTC, FoxxoTrystan requested changes
Test fails are still valid.

1 too much item.

2024-08-27 02:25 UTC, FoxxoTrystan approved these changes

2024-08-27 02:25 UTC, merged