Added cryogenics to Lighthouse
Fansana/floofstation1 pull request #211
Opened 2024-09-26 02:22 UTC by Eagle0600

# Description
Replaced cryosleep with cryogenics. Recent cryogenics changes and upcoming planned changes place cryogenics as a core medical tool rather than an extra gadget. As such, no medical bay can now be considered properly equipped without one. This will prevent people from going to cryosleep in medbay, but there's a more publicly accessible one near the dorms that serves this role better.

Added air alarms to the examination room, medical break room, and hydroponics; and added missing firelocks to the morgue and to chemistry. Several unlinked firelocks were linked to their nearby air alarms. This was a result of me messing around with the local atmospherics to support the cryogenics room and noticing several missing features. It does not constitute an audit of the map atmospherics, which may be required given what I found in and around medbay.

Fixed missing power to a single wall light in medbay next to the maintenance door. This section was rewired so that the morgue APC is now responsible for that stretch of maintenance. This means that the doors to medbay and to the morgue from maintenance can no longer be de-powered by cutting power stretching through maintenance from hydroponics.

<details><summary><h1>Media</h1></summary>
<p>

![cryogenics](https://github.com/user-attachments/assets/abc98acc-34dd-44fd-8951-5837e39296b0)

</p>
</details>

# Changelog

:cl:
- add: Lighthouse: Added cryogenics to medbay.
- remove: Lighthouse: Replaced the medbay cryosleep room with cryogenics.
- fix: Lighthouse: That one wall light in medbay next to maintenance now has power.

2024-09-26 17:12 UTC, Memeji approved these changes
Worth a shot to me, wait for Trystan's thoughts on the matter.

2024-09-27 20:54 UTC, FoxxoTrystan requested changes
Test fails valid.

2024-09-27 22:14 UTC, Eagle0600 commented
Unfortunately I am working this morning, but I'll take a look at it this afternoon.

2024-09-28 03:47 UTC, FoxxoTrystan approved these changes

2024-09-28 03:48 UTC, merged