Silly loadouts
Fansana/floofstation1 pull request #217
Opened 2024-09-29 02:35 UTC by Mnemotechnician

# Description
- Adds two leashes and a remote signaler to the Items loadout category
- Adds a shock collar to the Neck loadout category
- Adds a new Lewd loadout category, containing all lewd items featured by floof (it is going to be made a subcategory of Items after EE splits Items into separate subcategories [just a week away])

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/1c571a6b-1a0a-4437-a356-fef4d9c0707f)
![image](https://github.com/user-attachments/assets/f3ac5b94-8702-4361-a8fb-5aa9c072bd21)
![image](https://github.com/user-attachments/assets/853b49fa-a6d4-424c-b326-7537527dac0c)

</p>
</details>

---

# Changelog
:cl:
- add: Loadouts have been expanded with leashes, remote signalers, shock collars, and a wide variety of lewd items.

2024-09-29 02:54 UTC, FoxxoTrystan requested changes

2024-09-29 02:54 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Loadouts/itemsLewd.yml
> +  cost: 0
```suggestion
  cost: 2
```

2024-09-29 02:56 UTC, Mnemotechnician commented on Resources/Prototypes/Floof/Loadouts/itemsLewd.yml
> +  cost: 0
Yikes

2024-09-30 08:38 UTC, FoxxoTrystan approved these changes

2024-10-01 16:14 UTC, Memeji approved these changes

2024-10-01 16:14 UTC, merged