adding gekkering for vulps, emot keyword
Fansana/floofstation1 pull request #258
Opened 2024-10-12 07:48 UTC by neuPanda

# Description
added key word for vulp emotes: gekker

:cl:
- add: gekker for vulps

2024-10-12 11:42 UTC, Mnemotechnician commented on Resources/Prototypes/Voice/speech_emotes.yml
> +  chatMessages: [ laughs ]
```suggestion
  chatMessages: [ gekkers ]
```

2024-10-12 11:43 UTC, Mnemotechnician commented
This also should use a different sound collection, but uhhh... we will need to find some sounds for that I suppose.

2024-10-18 18:09 UTC, Memeji requested changes
Give it its own sound / sound collection, or add "gekkers" under the "Laugh" emote chat triggers.

2024-10-19 00:28 UTC, neuPanda commented
> Give it its own sound / sound collection, or add "gekkers" under the "Laugh" emote chat triggers.

adding it under the laugh emote triggers is it makes it available for all races if I am not mistaken. though it is possible I ended up with a tangled wire when trying to follow this

2024-10-19 23:37 UTC, Memeji approved these changes

2024-10-20 00:33 UTC, merged