Cryptobiolin Uplink injector
Fansana/floofstation1 pull request #322
Opened 2024-11-04 01:59 UTC by VividPups

# Description

This Make it so Nukies/Syndies can buy a 20u cryptobiolin  hypospray with 20u for 2 TC.
How many times have you been fucked over because someone had mind swap, mass sleep, or some other psionic that instantly ducks you over?
(You could also use it aggressively to insulate your target)
---

![image](https://github.com/user-attachments/assets/ff63d940-3aa5-4543-bf28-f216ca6d22e0)

# Changelog

:cl:
- add: New way for Syndies to deal with those pesky psionic

2024-11-04 03:20 UTC, Memeji requested changes
Test Fails are valid.
"UplinkCryoinjector" needs to only be in one file as right now it sees two with the same ID.

2024-11-04 04:11 UTC, VividPups commented
> Test Fails are valid. "UplinkCryoinjector" needs to only be in one file as right now it sees two with the same ID.

oh you know what I need to # it then. See the problem is that they arent showing up in the uplink unless its in the based file

2024-11-04 18:22 UTC, VividPups commented
Request was made

2024-11-04 19:27 UTC, VividPups commented
I will be changing some things to match the OG requested in the discord

2024-11-04 19:56 UTC, VividPups commented
Changes been made

2024-11-05 22:41 UTC, Memeji approved these changes
Test fail is false.
Those issues should have been resolved.

2024-11-05 22:56 UTC, VividPups commented
Is there a reason why it is causing these false fails?

2024-11-05 23:00 UTC, Memeji commented
> Is there a reason why it is causing these false fails?

Some prototypes causing issues that were recently fixed.
For some reason not caught by the system until NOW.

2024-11-06 13:09 UTC, FoxxoTrystan requested changes

2024-11-06 13:09 UTC, FoxxoTrystan commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +
Move this to Floof FTL Folders.

2024-11-07 04:43 UTC, FoxxoTrystan approved these changes

2024-11-07 04:47 UTC, merged