Combat boots
Fansana/floofstation1 pull request #335
Opened 2024-11-06 00:58 UTC by VividPups

Adds new combat boots to Sec

# Description
how many times have you as a secoff couldn't do your job because of space wind? way too fuckin much if you ask me. So therefor I made these boots. These boots are not only an item Oracle will request but also a Research item under riot control (space riots are real)  Now according to SOP mag boots are a restrictive item for engis meaning that Sec shouldn't be going out of their a way to find them and try and get them (Bad sec off) but, now this with this item Warden and HOS (After research) can regulate who can have them and when it can be handed out..
(Cost of making them can change really just didn't know what to put should probably be more steel that's for sure)

Also, this could help when later down the road we might finally be able to get nukies

# Media
![image](https://github.com/user-attachments/assets/629b2721-bf36-433d-a573-08ab92596992)

# Changelog

:cl:
- add: New Combat Boots!

2024-11-06 05:09 UTC, Memeji approved these changes

2024-11-06 13:13 UTC, FoxxoTrystan approved these changes
While good is good, Personnaly giving Security Magboots that does not slow down is a no-no for me.

MAGBOOTS SLOWS EVERYONE DOWN EXCEPT THE ADVANCED/EXPERIMENTAL ONES witch should be UNIQUE.

But regarding SOP that apprently "not everyone can use magboots" for me that bullshit too, magboots should be buildable in science at peoples request, ect...

I will put this under maintainer review.

2024-11-06 13:32 UTC, VividPups commented
> While good is good, Personnaly giving Security Magboots that does not slow down is a no-no for me.
> 
> MAGBOOTS SLOWS EVERYONE DOWN EXCEPT THE ADVANCED/EXPERIMENTAL ONES witch should be UNIQUE.
> 
> But regarding SOP that apprently "not everyone can use magboots" for me that bullshit too, magboots should be buildable in science at peoples request, ect...
> 
> I will put this under maintainer review.

The reason why I put it as no slow 

> While good is good, Personnaly giving Security Magboots that does not slow down is a no-no for me.
> 
> MAGBOOTS SLOWS EVERYONE DOWN EXCEPT THE ADVANCED/EXPERIMENTAL ONES witch should be UNIQUE.
> 
> But regarding SOP that apprently "not everyone can use magboots" for me that bullshit too, magboots should be buildable in science at peoples request, ect...
> 
> I will put this under maintainer review.

The reason why I put it at no slow down is because  amount of mobs that way to fast to have it like the regular the only real threats are the dragon, ninja and ratking all which have significantly faster and can kill their enemy. Also, I have not once have seen Advance or experimental magboots. (Unless you are talking about the single boots that CE has)

2024-11-06 13:36 UTC, FoxxoTrystan commented
> > While good is good, Personnaly giving Security Magboots that does not slow down is a no-no for me.
> > MAGBOOTS SLOWS EVERYONE DOWN EXCEPT THE ADVANCED/EXPERIMENTAL ONES witch should be UNIQUE.
> > But regarding SOP that apprently "not everyone can use magboots" for me that bullshit too, magboots should be buildable in science at peoples request, ect...
> > I will put this under maintainer review.
> 
> The reason why I put it as no slow
> 
> > While good is good, Personnaly giving Security Magboots that does not slow down is a no-no for me.
> > MAGBOOTS SLOWS EVERYONE DOWN EXCEPT THE ADVANCED/EXPERIMENTAL ONES witch should be UNIQUE.
> > But regarding SOP that apprently "not everyone can use magboots" for me that bullshit too, magboots should be buildable in science at peoples request, ect...
> > I will put this under maintainer review.
> 
> The reason why I put it at no slow down is because amount of mobs that way to fast to have it like the regular the only real threats are the dragon, ninja and ratking all which have significantly faster and can kill their enemy. Also, I have not once have seen Advance or experimental magboots. (Unless you are talking about the single boots that CE has)

Yes CE boots are normally unique, we are reviewing this and still go back to you.

2024-11-06 13:59 UTC, FoxxoTrystan requested changes
After a tiny talk here what i suggest, first advanced magboots is a nono but giving modified magboots for combat is fine to the security lathe, just make sure cost is not below normal magboots and make the research instead under "MagnetsTech", you will need to move ClothingShoesBootsMagCom under there.

Also i suggest that you could give them a custom/different sprite: here one from Frontier that could work: https://github.com/new-frontiers-14/frontier-station-14/tree/master/Resources/Textures/_NF/Clothing/Shoes/Boots/magboots-combat.rsi

Suggestion to assit you are below, if need assistance do tell.

2024-11-06 13:59 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/Shoes/Combatmags.yml
> +  parent: ClothingShoesBootsMagAdv
```suggestion
  parent: ClothingShoesBootsMag
```

2024-11-06 13:59 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/Shoes/Combatmags.yml
> +  description: Made by SESWC. These State-of-the-art magnetic boots that do not slow down their wearer with built in armor for extra protection
```suggestion
  description: Made by SESWC. These State-of-the-art magnetic boots with built in armor for extra protection
```
Edit description as needed.

2024-11-06 13:59 UTC, FoxxoTrystan commented on Resources/Prototypes/Research/arsenal.yml
> +  - ClothingShoesBootsMagCom #Floof
```suggestion
```

2024-11-06 13:59 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Recipes/Lathes/security.yml
> +    Gold: 100
```suggestion
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 500
```

Same cost as Science/Normal Magboots, feel free to add extra due to the small armor.

2024-11-06 13:59 UTC, FoxxoTrystan commented on Resources/Prototypes/Research/arsenal.yml
> +  - ClothingShoesBootsMagCom #Floof
Move this to MagnetsTech Instead.

2024-11-06 23:43 UTC, VividPups commented
> After a tiny talk here what i suggest, first advanced magboots is a nono but giving modified magboots for combat is fine to the security lathe, just make sure cost is not below normal magboots and make the research instead under "MagnetsTech", you will need to move ClothingShoesBootsMagCom under there.
> 
> Also i suggest that you could give them a custom/different sprite: here one from Frontier that could work: https://github.com/new-frontiers-14/frontier-station-14/tree/master/Resources/Textures/_NF/Clothing/Shoes/Boots/magboots-combat.rsi
> 
> Suggestion to assit you are below, if need assistance do tell.

the problem is again what is going to happen is that current antags are going to be much faster than the Secoff trying to defend the station which will just cost more deaths

2024-11-07 00:47 UTC, VividPups commented
> Current antags has the same problem as security regarding gravity, Magboots are toggable. wana walk normal speed? toggle it off.
> 
> No Gravity? Toggle it on.

and then you trip and die, or you toggle the antag gets in your range and kills you that's the problem.  it happen last night with a loneop

2024-11-07 00:50 UTC, FoxxoTrystan commented
> > Current antags has the same problem as security regarding gravity, Magboots are toggable. wana walk normal speed? toggle it off.
> > No Gravity? Toggle it on.
> 
> and then you trip and die, or you toggle the antag gets in your range and kills you that's the problem. it happen last night with a loneop

Then be carefull, even loneop/Syndicate magboots are not advanced.

2024-11-07 04:27 UTC, VividPups commented
all Request has been made

2024-11-07 04:29 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/Shoes/Combatmags.yml
> +    sprintModifier: 0.85
This need to be removed.
Pretty sure that is also not compatible with magboots.

2024-11-07 04:30 UTC, VividPups commented on Resources/Prototypes/Floof/Entities/Clothing/Shoes/Combatmags.yml
> +    sprintModifier: 0.85
those are when you aware it and I did remove it

2024-11-07 04:42 UTC, FoxxoTrystan approved these changes

2024-11-07 16:16 UTC, Memeji approved these changes

2024-11-07 22:38 UTC, Fansana requested changes
The shoes will need their own sprite. Working on it, do not merge.

2024-11-07 23:12 UTC, Fansana approved these changes

2024-11-08 00:42 UTC, merged