Hypnotemp Plushies
Fansana/floofstation1 pull request #356
Opened 2024-11-15 07:15 UTC by Cprn-Sprkl

# Description

Adds seven new HypnoTemp Staffer absorbent plushies. They can each hold 30u of liquid and come prefilled with different solutions for each variant. These plushies have been made findable in maintenance closets, maintenance wall lockers, and inside of prize balls.

The solutions have mostly mild and fun benefits such as small amounts of healing, slight speed boosts for a few seconds, and laughter. They're made up of mainly readily available chemicals with the exception of omnizine, which is available in the CMO variant plushie. The amount should be comparable to round start herbals while having no deterministic way of acquiring the CMO variant plushie.

<details><summary><h1>Media</h1></summary>
<p>

![HTPPreview](https://github.com/user-attachments/assets/03f2963e-1945-41bb-924f-1b5dc6c2e326)

</p>
</details>

---

# Changelog

:cl: sprkl
- add: Seven variants of HypnoTemp Staffer plushies can now be found in station lockers and prize balls.

2024-11-15 11:09 UTC, FoxxoTrystan requested changes
Some minors changes code wise.
While this is a self-insert, we will talk with the team regarding those.

2024-11-15 11:09 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Fun/prizeticket.yml
> +        orGroup: Prize
```suggestion
      # HypnoTemp Merch - Start
      - id: PlushieHypnoTempLO
        prob: 0.80
        orGroup: Prize
      - id: PlushieHypnoTempHoP
        prob: 0.80
        orGroup: Prize
      - id: PlushieHypnoTempCMO
        prob: 0.80
        orGroup: Prize
      #HypnoTemp Merch - End
```

2024-11-15 11:09 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Fun/prizeticket.yml
> +        orGroup: Prize
```suggestion
      # HypnoTemp Merch - Start
      - id: PlushieHypnoTempMysta
        prob: 0.50
        orGroup: Prize
      - id: PlushieHypnoTempHoS
        prob: 0.50
        orGroup: Prize
       #HypnoTemp Merch - End
```

2024-11-15 11:09 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Fun/prizeticket.yml
> +      - id: PlushieHypnoTempCap
```suggestion
      - id: PlushieHypnoTempCap # Floofstation
```

2024-11-15 11:09 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/HypnoTempPlushies/staffer_plushies.rsi/meta.json
> +    "copyright": "JTCircus",
I suggest providing more information, like discord ID, github account, ect... this is fine too

2024-11-15 11:09 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Objects/HypnoTempPlushies/HypnoTempPlushies.yml
Pretty sure we will not allo Hypo Plush, but we will review this after some talk.

2024-11-15 11:21 UTC, FoxxoTrystan requested changes
Tests fails are valid.

2024-11-18 18:52 UTC, Fansana commented
can you add this to the plush vendor?

2024-11-18 19:50 UTC, Fansana approved these changes

2024-11-19 04:15 UTC, FoxxoTrystan commented
While they are in the random prizeball ticket, they are not in the prizevendor.

2024-11-21 15:37 UTC, FoxxoTrystan requested changes

2024-11-21 15:37 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Objects/HypnoTempPlushies/HypnoTempPlushies.yml
Actully im against this, Hypno Plushies for everyone that look in maintenance is a big nono.

Il prefer the plushie is not a hypno item or is not findable in maintenance.

2024-11-21 16:07 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Objects/HypnoTempPlushies/HypnoTempPlushies.yml
They act like a hypo item correct? they can contain solutions.

2024-11-21 17:08 UTC, FoxxoTrystan approved these changes

2024-11-21 17:08 UTC, merged