Blood Red Coder Socks Addition
Fansana/floofstation1 pull request #37
Opened 2024-07-18 19:27 UTC by Shiro69420

Hello all silly billys. I have made a hopefully wonderful addition. BLOOD RED CODER SOCKS! Its recolored coder socks in the colors of blood red magboots. The code has it where there is 3 inside of the pride-o-mat in emag storage (for fellow syndicates). It also has it for 1 TC in the pointless section of the syndicate uplink.

2024-07-18 20:06 UTC, FoxxoTrystan requested changes
Please follow the correct PR Format, this will not be merged until its is fixed.

Code is code overall with just one code suggestions, good job.

2024-07-18 20:06 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/pride.yml
> +      ClothingUnderSocksCoderValid: 3
```suggestion
      ClothingUnderSocksCoderValid: 3 # Floofstation
```

2024-07-18 20:28 UTC, FoxxoTrystan approved these changes

2024-07-19 06:43 UTC, Fansana approved these changes

2024-07-19 07:13 UTC, merged