Mining Drill
Fansana/floofstation1 pull request #383
Opened 2024-11-27 21:01 UTC by fenndragon

# Description

This pull request fixes the mining drill to have it's stats back to expected values and performance. 

---

# Changelog

:cl:
- fix: Fixed mining drill

2024-12-02 22:25 UTC, fenndragon commented
> Reduce the blunt and slash damage to match the new attack rate. Something like around ~2 or ~1 for them.

ah- I had not noticed the values for the damage on our drill were not the same as frontier, I will gladly change it to match properly

2024-12-02 22:27 UTC, fenndragon commented
> Reduce the blunt and slash damage to match the new attack rate. Something like around ~2 or ~1 for them.

alright, I adjusted the damages to match the drill previously, on frontier it deals 3 "brute" so I put 2 blunt, 1 slash, and it deals 15 structural

2024-12-02 22:57 UTC, Memeji requested changes
I would reduce the blunt stamina damage factor to 1 and make the heavy stamina cost somewhere around ~1 or ~2.

Or make the heavy cost 0 but reduce the heavy range modifier to 1

2024-12-03 00:03 UTC, fenndragon commented
> I would reduce the blunt stamina damage factor to 1 and make the heavy stamina cost somewhere around ~1 or ~2.
> 
> Or make the heavy cost 0 but reduce the heavy range modifier to 1

these settings are to remove the stamina use from the equation entirely, it's a proof of concept in the form of a "weapon" that's not used against people to see if the change is a welcome one. 

if it goes well I intend to look into making edits to other melee weapons to fix the current system which makes you fall on your face after a few swings.

2024-12-03 00:17 UTC, Memeji commented
Will be testing this on my local instance to see the details and how it works out.

2024-12-06 20:21 UTC, Memeji approved these changes
Went over these changes, worth a try on live to see how it works out.

2024-12-07 06:16 UTC, FoxxoTrystan approved these changes

2024-12-07 06:16 UTC, merged