added new drinks, edited filesystem
Fansana/floofstation1 pull request #39
Opened 2024-07-19 19:34 UTC by SleepyScarecrow

# Description

Added in 12 new mixed drinks, 2 new bottles to the booze'o'mat, and edited some filesystem stuff that didn't make sense to me. 
The drinks are to give pomjuice and the new aphrodisiacs another purpose, and unfortuantely the bottle'o'cum is just pandering to the masses. The filesystem stuff I changed was simple enough-- there used to be Resources/Prototypes/Floof/ as well as Resources/Prototypes/Floofstation/, I simply merged these both into Resources/Prototypes/Floofstation to make things a bit cleaner.

---

# TODO

- [ ] Pomegranate Foods
- [x] Pomegranate Cocktails

---

<details><summary><h1>Additions</h1></summary>
<p>

![Example Media Embed](https://cdn.discordapp.com/attachments/1261497448019529790/1263939111392378920/image.png?ex=669c0e87&is=669abd07&hm=e4f0c8f12169961bad739a221c980645bd23540b058b8a78483337f9cbdca635&)
![Example Media Embed]
(https://cdn.discordapp.com/attachments/1261497448019529790/1263940347675938919/2024-07-19_15-25-20.mp4?ex=669c0fad&is=669abe2d&hm=3f6cdec1ba6ab7475a46e88f37dc480196764bdfe48f356de230736d575a4baf&)
</p>
</details>

---

# Changelog

:cl: Tilkku
- add: Added a new series of cocktails and new bottles to the booze'o'mat
- tweak: Tweaked filesystem stuff for easier additions in the future

2024-07-19 20:07 UTC, FoxxoTrystan commented
Did not made a review yet as Linter is unhappy, you should fix that.

Also there no need to put changelogs or code related things, changelogs should only be "in-game"/player related changes, not code or directory, if theres changes please state it in the description, witch you did.

2024-07-19 21:10 UTC, SleepyScarecrow commented
made linter happy

2024-07-20 13:12 UTC, FoxxoTrystan commented
Also please do not use discord link for media, just paste it directly in github.

2024-07-20 13:21 UTC, FoxxoTrystan requested changes
PR is good, nice change of directory but please make copyright a bit more detailed to find the author if needed, unless the autho wish to not be found.

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/anisettebottle.rsi/meta.json
> +    "copyright": "discord: dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/blueballer.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/bottleocum.rsi/meta.json
> +    "copyright": "discord: dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/demonseed.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/doublecreamblaster.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/emeraldswinger.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/mariejulep.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/orgasmonthebeach.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/pompassion.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/redrocket.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/semenbomb.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/semenhemorrhage.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/watermelonginjizz.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 13:21 UTC, FoxxoTrystan commented on Resources/Textures/Floof/Objects/Consumable/Drinks/yeolhandy.rsi/meta.json
> +    "copyright": "Made by dakodragon",
Please provide more information
example:

Made by dakodragon (Discord: DiscordID)

2024-07-20 18:22 UTC, FoxxoTrystan requested changes
DiscordID: dakodragon
 
is incorrect and ID is a string of number.

"Made by dakodragon, DiscordID: 1" example.

2024-07-20 18:28 UTC, FoxxoTrystan approved these changes

2024-07-22 17:10 UTC, Fansana approved these changes

2024-07-22 20:15 UTC, merged