The CUM update - First iteration.
Fansana/floofstation1 pull request #49
Opened 2024-07-21 06:21 UTC by Memeji

# Description

This update adds two traits (Cock, Boobs) and ways to make cum and milk using them.

---

# TODO

- [ ] Check for suit (except loincloth) to prevent action.
- [ ] Be able to cum/milk w/o a container in hand.
- [ ] Better text for actions.
- [ ] Clean the code better/Make it better (I know you're gonna bully me, Trystan. Lol)

---

# Changelog

:cl:
- add: "Cock" trait, fill containers with your essence!
- add: "Boobs" trait, fill containers using your mommy milkers!
- tweak: Changed hunger/thirst values for cum to not satiate as much. (No cum meta)

2024-07-21 21:16 UTC, FoxxoTrystan reviewed
HasBoobs and HasCock as just the same system, just add 2 component but they use the same system to CockComponent use "LewdSystem" or i dunno how you wana call it but avoid using 2 Systems thats are mostly copy and paste, i recomend also using .yml so instead you also do only 1 Component and System just regrouping them under 1, look how languages are listed by example.

I will fully review this later so for now this is a comment and not requested changes.

2024-07-22 16:53 UTC, Fansana commented
I'm unsure if one component can handle all the things we want in the future. For one thing the functionality will be different between each. Breasts will be drinkable but cock not. Cocks will have the cum verb attached which allows them to eject special content.

2024-07-22 19:26 UTC, Memeji commented
Lemme know how you'd like to move forward with this. As well as how I would make those changes to this PR!

2024-07-22 20:09 UTC, FoxxoTrystan commented
Il give it a proper review tomorrow.

2024-07-23 15:08 UTC, FoxxoTrystan requested changes
HasBoobsSystem and HasPenisSystem just compleatly does the same thing, this need to be regrouped into one system, by using multiple component or .yml files.

Im willing to assist or make some commits if you need asisstance.

Theres also some functions that are outated but i will point those issues out later after the main issue is fixed.

2024-08-05 18:33 UTC, Fansana approved these changes

2024-08-05 19:18 UTC, FoxxoTrystan requested changes
I fixed merge conflicts but now test are failing due to some component not being valid, this need to be fixed.

2024-08-05 21:23 UTC, FoxxoTrystan requested changes

2024-08-05 21:23 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> +             !EntityManager.HasComponent<RefillableSolutionComponent>(args.Using.Value)) //see if removing this part lets you milk on the ground.
```suggestion
             !args.CanInteract ||
             args.User != args.Target ||
             !EntityManager.HasComponent<RefillableSolutionComponent>(args.Using.Value)) //see if removing this part lets you milk on the ground.
```

2024-08-05 21:23 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> +             !EntityManager.HasComponent<RefillableSolutionComponent>(args.Using.Value)) //see if removing this part lets you milk on the ground.
```suggestion
             !args.CanInteract ||
             args.User != args.Target ||
             !EntityManager.HasComponent<RefillableSolutionComponent>(args.Using.Value)) //see if removing this part lets you milk on the ground.
```

2024-08-05 22:07 UTC, FoxxoTrystan approved these changes
Honestly, this will need updates, refractors, ect... to be improved but so far, right now.

This is fine.

2024-08-05 22:07 UTC, merged

2024-11-24 15:23 UTC, Leviathan21 commented
every dya we strafe further from god