Aine longcoats
Fansana/floofstation1 pull request #59
Opened 2024-07-24 22:48 UTC by foxcumberland

# Description

Double-breasted **longcoats** for almost everyone! Includes one for each unit of Command, three for Security Staff (Corpsman, Warden, Secoff), and four general-purpose ones (Brown, Black, Nanotrasen and an Arashi Labs 'medical' colored one, and of course a green version of the Captain's for Central Command.

Command, Corpsman and Warden Longcoats are added to their respective lockers. The basic Armored Longcoat has two copies in the SecTech between the Durathread Vest and Plate Carrier (as it is statistically analagous to them) while the four general longcoats are in the ClothesMate.

Designs are in media.

---

# TODO

Add at least the general longcoats to loadouts.

_Possibly_ add Corporate Jacket versions, need to discuss item bloat at some point as adding _a dozen_ jackets into the ClothesMate is going to make that list very, very long...

---

<details><summary><h1>Media</h1></summary>
<p>

![Poster](https://github.com/user-attachments/assets/299c65e4-528f-4851-b1f0-8c7ee3aa6034)

</p>
</details>

---

# Changelog

:cl:

- Initial Commit

2024-07-25 00:35 UTC, FoxxoTrystan commented
Before i do any changes, this PR feels its will fit better in upsteam: https://github.com/Simple-Station/Einstein-Engines/

I have run also the test and RSI seme angry, this will need fixes.

2024-07-25 00:35 UTC, FoxxoTrystan commented
And changlog will need to be different please.

2024-07-25 00:46 UTC, foxcumberland commented
> Before i do any changes, this PR feels its will fit better in upsteam: https://github.com/Simple-Station/Einstein-Engines/
> 
> I have run also the test and RSI seme angry, this will need fixes.

I won't lie, I have no idea what any of that or the other review stuff means yet, I have no idea what a fail means and I don't know if that's somehow something I added causing a break or something else.

Changelog can be made real, I just had my brain in the wrong space as to what the changelog was referencing (updates to the pr rather than updates to the master)

Probably could be done upstream but I don't need the anxiety of trying to publish something to a group that I don't know, to people that I don't have any real contact with yet or am comfortable asking for help, when I'm just figuring this stuff out.

2024-07-25 01:08 UTC, FoxxoTrystan requested changes
Armor Stats need talk.
Copyright need to be set and not "modified later".
Comments are needed on Floof to not be overridden and so we know where its comes, follow suggestions.

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: ClothingLongcoatWarden
```suggestion
      - id: ClothingLongcoatWarden
```
```suggestion
      - id: ClothingLongcoatWarden # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: ClothingLongcoatWarden
```suggestion
      - id: ClothingLongcoatWarden # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: ClothingLongcoatBrigmedic
```suggestion
      - id: ClothingLongcoatBrigmedic # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: ClothingLongcoatBrigmedic
```suggestion
      - id: ClothingLongcoatBrigmedic # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
> +    ClothingLongcoatBlack: 2
```suggestion
    ClothingLongcoatNT: 2 # Floofstation
    ClothingLongcoatAL: 2 # Floofstation
    ClothingLongcoatBrown: 2 # Floofstation
    ClothingLongcoatBlack: 2 # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml
> +    ClothingLongcoatSec: 1
```suggestion
    ClothingLongcoatBrown: 1 # Floofstation
    ClothingLongcoatSec: 1 # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
> +    ClothingLongcoatSec: 2
```suggestion
    ClothingLongcoatSec: 2 # Floofstation
```

2024-07-25 01:08 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Entities/Clothing/OuterClothing/wintercoats.yml
Are the armor here normal? as if i remember we avoid to add armor mostly to civillians

2024-07-25 01:30 UTC, foxcumberland commented on Resources/Prototypes/Floof/Entities/Clothing/OuterClothing/wintercoats.yml
suggestions committed. For the armor values, I figured it'd be cute to have, but if it's a problem, I don't mind removing those values entirely.

2024-07-25 01:34 UTC, foxcumberland commented
> I do wana note that upsteam is not wizden but upsteam.

I know it's not wizden, but otherwise this... just confused me. Is upstream not what we call the EE code/team, because That's what I was referring to when I meant people I don't know.

2024-07-25 01:49 UTC, FoxxoTrystan commented
RSI / Linter test failed, click details and fix the issues displayed.
If unble to find the error, feel free to ping me on discord.

2024-07-25 04:21 UTC, Fansana commented
I really like this. We can merge this upstream if need be that shouldn't be a problem.
Please fix the following errors so we can merge it
Resources/Textures/Floof/Clothing/OuterClothing/WinterCoats/longcoatAL.rsi: PNG not defined in metadata: Icon.png
Resources/Textures/Floof/Clothing/OuterClothing/WinterCoats/longcoatAL.rsi: icon: failed to open state icon.png

2024-07-27 06:21 UTC, Fansana approved these changes

2024-07-29 14:38 UTC, FoxxoTrystan commented
RSI:
Resources/Textures/Floof/Clothing/OuterClothing/WinterCoats/longcoatAL.rsi: PNG not defined in metadata: Icon.png
Resources/Textures/Floof/Clothing/OuterClothing/WinterCoats/longcoatAL.rsi: icon: failed to open state icon.png

YAML Linter:
Unable to load RSI '/Textures/Floof/Clothing/OuterClothing/WinterCoats/longcoatAL.rsi'.

Check failed tests for more information.

2024-07-31 00:59 UTC, foxcumberland commented
RSI/YAML fixed, I believe. Got to love all that angry error text just for a simple filename capitalization goof.

2024-07-31 01:16 UTC, FoxxoTrystan requested changes
Linter still uhappy:

Error: /Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml(98,5)  PrototypeID ClothingLongcoatNT for type Robust.Shared.Prototypes.EntityPrototype at Line: 98, Col: 5 not found
Error: /Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml(99,5)  PrototypeID ClothingLongcoatAL for type Robust.Shared.Prototypes.EntityPrototype at Line: 99, Col: 5 not foun

2024-07-31 01:17 UTC, FoxxoTrystan commented
> RSI/YAML fixed, I believe. Got to love all that angry error text just for a simple filename capitalization goof.
> 
> Edit: Nevermiiind it was showing me green until it failed...

Yeah because its your first PR here, i have to aprove the tests myself.

2024-07-31 01:24 UTC, foxcumberland commented
Should be good now, LongcoatNT and LongcoatAL were newer names before that the files got but the prototype didn't.

2024-07-31 04:49 UTC, FoxxoTrystan approved these changes

2024-07-31 05:11 UTC, merged